Development (#15): service worker effort and refactoring
* init jest

* update tsconfig and husky pre-commit

* send timer messages to serviceworker

* set timer in serviceworker

* add serviceworker logging

* try serviceworker in typescript

* remove timer drawer

* remove assets and settings

* enforce typescript strict mode

* init eslint

* only lint staged files and more lint rules

* fix lint errors

* quiet serviceworker

* init trpc

* add as prop on home links

* try trpc url right in _app

* Fix trpc build error (#14)

* console log url

* change to API_URL

* reset url

* working ssg

* ssg recipe details

* remove unused images

* start a baking steps page

* add links to baking page

* baking steps with progress bar

* progress colors and start again button

* header title link back to recipe details

* slide in step changes

* add missed ProgressSteps

* get recipe key off url query

* fix default initialValue function

* fix baseUrl for browser

* show next prev step buttons

* keyboard moving slides

* move extra step buttons under card

* memoize baking page for linting

* use vertical rows and flex

* satisfy no unused var linting

* eslint ignores d ts files

* start recipe button

* improve recipe link hover and start button color

* prevent updating recipekey on first render

* hide baking process feature

* test setInterval

* fix pass endtimenumber to start timer

* request notification permission on startTimer

* remove unused styled component

* set up locatorJS

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,25 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-yarn tsc --noEmit
+# lint only staged files
+for file in $(git diff --diff-filter=d --cached --name-only | grep -E '\.(js|jsx|ts|tsx)$')
+do
+  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
+  if [ $? -ne 0 ]; then
+    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
+    exit 1 # exit with failure status
+  fi
+done
+
+# yarn next lint
+
+# use yarn if available
+if command -v yarn >/dev/null 2>&1; then
+  yarn typecheck
+  # else use pnpm
+elif command -v pnpm >/dev/null 2>&1; then
+  pnpm run typecheck
+else # fallback to npm
+  npm run typecheck
+fi
+
